import AppCard from "components/AppCard";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { motion } from "framer-motion";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-wrap gap-5 h-full overflow-auto">
        {new Array(10).fill(1).map((_, i) => (
          <AppCard id={Math.random().toString()} variant="horizontal" key={i} />
        ))}
        <motion.div layout="preserve-aspect" layoutId="hello">
          <AppCard id={Math.random().toString()} variant="horizontal" />
        </motion.div>
      </div>
    </>
  );
};

export default Home;
