import { useRef } from "react";
import AppCard from "components/AppCard";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { motion } from "framer-motion";
import { useRouter } from "next/router";
import HeroCards from "components/HeroCards";
import { HeroSection } from "components/pageSections/Home";
const Home: NextPage = () => {
  const {} = useRouter();
  const containerRef = useRef<HTMLDivElement>(null);
  return (
    <div className="h-full overflow-auto" ref={containerRef}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection containerRef={containerRef} />
      <div className="px-5">
        <div className="flex flex-wrap  gap-5 mb-5">
          {data.map((_, i) => (
            <AppCard id={_ + "123"} key={i} />
          ))}
        </div>
        <div className="flex flex-wrap gap-5">
          {data.map((_, i) => (
            <AppCard isVertical id={_} key={i} />
          ))}
        </div>
      </div>
    </div>
  );
};

const data = new Array(10).fill(1).map((i) => Math.random().toString());

export default Home;
